version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: localhost
    command: 
      - sh
      - -c
      - |
        # Wait for Zookeeper to be ready
        while ! nc -z zookeeper 2181; do sleep 1; done;
        # Create topics
        /etc/confluent/docker/run &
        sleep 5;
        kafka-topics --create --topic scheduled --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1;
        kafka-topics --create --topic uppercase --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1;
        kafka-topics --create --topic dead-letter-topic-uppercase --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1;
        # Keep the container running
        tail -f /dev/null

networks:
  default:
    name: kafka-network
